<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicholas Shuckerow">
<meta name="dcterms.date" content="2024-07-01">

<title>Nick_Shuckerow - Throughput</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Nick_Shuckerow</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#basic-analysis" id="toc-basic-analysis" class="nav-link active" data-scroll-target="#basic-analysis">Basic Analysis</a>
  <ul class="collapse">
  <li><a href="#converting-datetime" id="toc-converting-datetime" class="nav-link" data-scroll-target="#converting-datetime">Converting Datetime</a></li>
  <li><a href="#calculating-inventory-and-creating-inventory-build-up-diagram" id="toc-calculating-inventory-and-creating-inventory-build-up-diagram" class="nav-link" data-scroll-target="#calculating-inventory-and-creating-inventory-build-up-diagram">Calculating Inventory and creating Inventory Build-Up Diagram</a></li>
  </ul></li>
  <li><a href="#customers-entering-every-15-min" id="toc-customers-entering-every-15-min" class="nav-link" data-scroll-target="#customers-entering-every-15-min">Customers entering every 15 Min</a></li>
  <li><a href="#comparing-littles-law-calculations-to-data" id="toc-comparing-littles-law-calculations-to-data" class="nav-link" data-scroll-target="#comparing-littles-law-calculations-to-data">Comparing Little’s Law Calculations to Data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Throughput</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicholas Shuckerow </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Throughput is a commonly used metric in supply chain analytics. It is the rate at which products, material, people, or information move through the supply chain from point of origin to the point of consumption.</p>
<p>If we were speaking of a product or material, you could measure throughput from the supplier (origin) to the customer (end point). In manufacturing, it could be from when the process starts of building or assembling the material, until that process is complete.</p>
<p>Throughput is essential to a number of practical uses, some of them being customer experience, staffing levels, store layout, or queue management.</p>
<p>The formula for throughput is fairly simple:</p>
<p><span class="math display">\[ L = \lambda * W \]</span></p>
<p>Where:</p>
<ul>
<li>L is the average number of customers, products, etc in the location, store or facility</li>
<li><span class="math display">\[ \lambda \]</span> is the effective arrival rate</li>
<li>W is the average time spent in the process</li>
</ul>
<p>Today, we’ll be calculating the parameters within Little’s Law and comapring them to our data, while also creating an inventory build up diagram for a small grocery store named Roger’s Market. Roger’s Market uses Amazon Walk Out technology to track a customers time in a store. We’ll be using the data from the store and the Walk Out technology to determine our average trip duration per customer.</p>
<section id="basic-analysis" class="level1">
<h1>Basic Analysis</h1>
<p>As always, we want to load and describe our data. Below describes some of the less straightforward features within our data set.</p>
<ul>
<li><p>Purchase_datetime: It is a purchase time. Consider it as an exit time from the store</p></li>
<li><p>Transaction_id: It is a group(person) &amp; item identifier.</p></li>
<li><p>Session_id: It is a group/person identifier, i.e., the first three transactions are three items that <em>ONE</em> person bought. Notice that those three transactions have the same purchase_datetime.</p></li>
<li><p>Trip_duration_mins: It is how long a customer/a group of customers spend within the store. So, purchase_datetime - trip_duration_mins = an entry time to the store.</p></li>
<li><p>Group_size: how many customers came into the store as a group. One customer in that group will pay all together.</p></li>
</ul>
<p>Now lets load the data.</p>
<div id="3303d724" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_91843/1611834843.py:7: DtypeWarning:

Columns (0,1,2,8,9,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">store_id</th>
<th data-quarto-table-cell-role="th">purchase_datetime</th>
<th data-quarto-table-cell-role="th">product_title</th>
<th data-quarto-table-cell-role="th">sku</th>
<th data-quarto-table-cell-role="th">currency</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">quantity</th>
<th data-quarto-table-cell-role="th">total_price</th>
<th data-quarto-table-cell-role="th">type_of_transaction</th>
<th data-quarto-table-cell-role="th">transaction_id</th>
<th data-quarto-table-cell-role="th">transaction_datetime</th>
<th data-quarto-table-cell-role="th">session_id</th>
<th data-quarto-table-cell-role="th">product_category</th>
<th data-quarto-table-cell-role="th">product_subcategory</th>
<th data-quarto-table-cell-role="th">entry/exit_method</th>
<th data-quarto-table-cell-role="th">trip_duration_mins</th>
<th data-quarto-table-cell-role="th">group_size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>HDHRoger'sMarket</td>
<td>2/28/2024 7:03</td>
<td>Cheetos Flamin Hot Limon</td>
<td>2.840005e+10</td>
<td>NaN</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>order</td>
<td>aadae6df-aeb4-4d42-86c4-4cb41dee44a6</td>
<td>NaN</td>
<td>ee05da65-08a6-40e8-bad0-cc97cbb979b0</td>
<td>NTPM-JWO-GR CHIPS</td>
<td>NTPM-JWO-GR CHIPS</td>
<td>App</td>
<td>1.0666</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>HDHRoger'sMarket</td>
<td>2/28/2024 7:03</td>
<td>Trolli Sour Brite Crwlrs Berry</td>
<td>4.142012e+10</td>
<td>NaN</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>order</td>
<td>b89ffb88-46dc-43cb-9e7c-ec8e3d32a877</td>
<td>NaN</td>
<td>ee05da65-08a6-40e8-bad0-cc97cbb979b0</td>
<td>NTPM-JWO-GR CANDY</td>
<td>NTPM-JWO-GR CANDY</td>
<td>App</td>
<td>1.0666</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>HDHRoger'sMarket</td>
<td>2/28/2024 7:03</td>
<td>Turkey &amp; Cheddar Sandwich</td>
<td>9.999910e+10</td>
<td>NaN</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>order</td>
<td>0c9ed66e-0e97-4b4b-be1a-52d44d042c07</td>
<td>NaN</td>
<td>ee05da65-08a6-40e8-bad0-cc97cbb979b0</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>App</td>
<td>1.0666</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>HDHRoger'sMarket</td>
<td>2/28/2024 7:09</td>
<td>Pepperoni Protein Pack</td>
<td>9.999910e+10</td>
<td>NaN</td>
<td>NaN</td>
<td>3.0</td>
<td>NaN</td>
<td>order</td>
<td>01a6c049-a7f4-45ee-84fc-3fb8c9d7fc7a</td>
<td>NaN</td>
<td>51be7741-b716-4478-be50-ef2b5f52d69d</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>App</td>
<td>0.9500</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>HDHRoger'sMarket</td>
<td>2/28/2024 7:09</td>
<td>Dnkn Dnts Iced Coffee Vanilla</td>
<td>4.900007e+10</td>
<td>NaN</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>order</td>
<td>20bc02c6-bd1f-45c3-89c9-7dc1d9f6f259</td>
<td>NaN</td>
<td>e63a092b-2814-4358-a2f9-e9354c72d829</td>
<td>NTPM-JWO-BEVERAGES</td>
<td>NTPM-JWO-BEVERAGES</td>
<td>App</td>
<td>0.8500</td>
<td>1.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="20d267ba" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>rogers.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 125544 entries, 0 to 125543
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   store_id              4645 non-null   object 
 1   purchase_datetime     4645 non-null   object 
 2   product_title         4645 non-null   object 
 3   sku                   4645 non-null   float64
 4   currency              0 non-null      float64
 5   price                 0 non-null      float64
 6   quantity              4645 non-null   float64
 7   total_price           0 non-null      float64
 8   type_of_transaction   4645 non-null   object 
 9   transaction_id        4645 non-null   object 
 10  transaction_datetime  0 non-null      float64
 11  session_id            4645 non-null   object 
 12  product_category      4645 non-null   object 
 13  product_subcategory   4645 non-null   object 
 14  entry/exit_method     4645 non-null   object 
 15  trip_duration_mins    4645 non-null   float64
 16  group_size            4645 non-null   float64
dtypes: float64(8), object(9)
memory usage: 16.3+ MB</code></pre>
</div>
</div>
<p>From viewing the data and info for the data, we see that some of the columns are in datetime format. Python handles datetime differently, which means we’ll need to do some conversion to get it to minutes.</p>
<p>We also find that columns of currency, price, total_price, and transaction datetime have all null values. Transaction datetime would be useful, but we do have entry_datetime, purchase_datetime, and trip duration, so we can still use that data for our purpose.</p>
<p>Let’s drop those columns which have all NaN values and see if there are any duplicates in this data as well.</p>
<div id="881775bf" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping columns which have all NaN values</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rogers <span class="op">=</span> rogers.drop([<span class="st">'currency'</span>, <span class="st">'price'</span>, <span class="st">'total_price'</span>, <span class="st">'transaction_datetime'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting how many duplicated rows of data are present</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>rogers.duplicated().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>120898</code></pre>
</div>
</div>
<p>There are 120,098 duplicates out of the 125,544 data points! From running rogers.info(), we know we should have 4,645 rows of data (non-null values).</p>
<div id="d1720776" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping duplicated rows</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>rogers <span class="op">=</span> rogers.drop_duplicates(subset<span class="op">=</span>[<span class="st">'purchase_datetime'</span>, <span class="st">'transaction_id'</span>, <span class="st">'session_id'</span>, <span class="st">'trip_duration_mins'</span>, <span class="st">'group_size'</span>])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># New shape of dataframe after dropping duplicated rows</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>rogers.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>(4646, 13)</code></pre>
</div>
</div>
<p>So now there are 4,646 rows after dropping duplicates. That is one row off from what we anticipated. The next thing to do is check for N/A values.</p>
<p>We’ll create a function which checks each column for NA values, then records the row indices that have NA values for each column.</p>
<div id="d4dc6527" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_na_indices(dataframe):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    na_indices <span class="op">=</span> {}</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column <span class="kw">in</span> dataframe.columns:</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        na_rows <span class="op">=</span> dataframe.index[dataframe[column].isna()].tolist()</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        na_indices[column] <span class="op">=</span> na_rows</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> na_indices</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>na_results <span class="op">=</span> get_na_indices(rogers)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>na_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>{'store_id': [4645],
 'purchase_datetime': [4645],
 'product_title': [4645],
 'sku': [4645],
 'quantity': [4645],
 'type_of_transaction': [4645],
 'transaction_id': [4645],
 'session_id': [4645],
 'product_category': [4645],
 'product_subcategory': [4645],
 'entry/exit_method': [4645],
 'trip_duration_mins': [4645],
 'group_size': [4645]}</code></pre>
</div>
</div>
<p>We can see that all the NA values are in row index 4645 (which is equivalent to the 4656 row since python starts index counting at 0).</p>
<p>We’ll drop row index 4645.</p>
<div id="67d219cd" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>rogers <span class="op">=</span> rogers.drop(index <span class="op">=</span> <span class="dv">4645</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>rogers.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>(4645, 13)</code></pre>
</div>
</div>
<p>But before we proceed with our data analysis, let’s take another look at the session_id variable. As described the session_id is for one session from one customer. If there are multiple of the same session_id’s, that means it was from the same customer, and should have the exact same session_id, purchase_datetime, trip_duration, and group_size.</p>
<p>Let’s count how many unique session_id’s we have.</p>
<div id="b0201d07" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rogers.session_id.nunique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>2183</code></pre>
</div>
</div>
<p>There are only 2,183 unique session ID’s, but we have 4,645 rows of data still. Let’s drop the duplicated session ID’s so there is only one row remaining for each session ID.</p>
<div id="a93906d9" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rogers <span class="op">=</span> rogers.drop_duplicates(subset <span class="op">=</span> <span class="st">'session_id'</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>rogers.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>(2183, 13)</code></pre>
</div>
</div>
<p>We still have one extra row of data. Where could it be?</p>
<p>Let’s use dropna from the columns to see if anything is being dropped.</p>
<div id="8e7a7e31" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rogers.dropna()</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>rogers.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>(2183, 13)</code></pre>
</div>
</div>
<section id="converting-datetime" class="level2">
<h2 class="anchored" data-anchor-id="converting-datetime">Converting Datetime</h2>
<p>To find throughput, we want to know how many customers are present in the store at every minute and the rate of their arrival. Knowing how many customers are in the store every minute will allow us to make an inventory build-up diagram.</p>
<p>But first, we need to know what each individual’s entry time is before we can know how many are in the store every minute.</p>
<p>To calculate entry time, we’ll need to subtract the trip duration in minutes from the purchase_datetime.</p>
<p>Knowing python formatting and working through this in the past, I know the current format of purchase_datetime (M/DD/YYYY HH:MM) will cause issues when subtracting another datetime if they’re not in the same format. The default format in python for datetime is (YYYY-MM-DD HH:MM:SS), so we’ll need to convert that.</p>
<p>I also know that we’ll need to convert trip duration in minutes from its current decimal form to datetime format.</p>
<div id="15f81a35" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rogers[<span class="st">'purchase_datetime'</span>] <span class="op">=</span> pd.to_datetime(rogers[<span class="st">'purchase_datetime'</span>])</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>rogers[<span class="st">'entry_datetime'</span>] <span class="op">=</span> rogers[<span class="st">'purchase_datetime'</span>] <span class="op">-</span> pd.to_timedelta(rogers[<span class="st">'trip_duration_mins'</span>], unit<span class="op">=</span><span class="st">'m'</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>rogers.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">store_id</th>
<th data-quarto-table-cell-role="th">purchase_datetime</th>
<th data-quarto-table-cell-role="th">product_title</th>
<th data-quarto-table-cell-role="th">sku</th>
<th data-quarto-table-cell-role="th">quantity</th>
<th data-quarto-table-cell-role="th">type_of_transaction</th>
<th data-quarto-table-cell-role="th">transaction_id</th>
<th data-quarto-table-cell-role="th">session_id</th>
<th data-quarto-table-cell-role="th">product_category</th>
<th data-quarto-table-cell-role="th">product_subcategory</th>
<th data-quarto-table-cell-role="th">entry/exit_method</th>
<th data-quarto-table-cell-role="th">trip_duration_mins</th>
<th data-quarto-table-cell-role="th">group_size</th>
<th data-quarto-table-cell-role="th">entry_datetime</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>HDHRoger'sMarket</td>
<td>2024-02-28 07:03:00</td>
<td>Cheetos Flamin Hot Limon</td>
<td>2.840005e+10</td>
<td>1.0</td>
<td>order</td>
<td>aadae6df-aeb4-4d42-86c4-4cb41dee44a6</td>
<td>ee05da65-08a6-40e8-bad0-cc97cbb979b0</td>
<td>NTPM-JWO-GR CHIPS</td>
<td>NTPM-JWO-GR CHIPS</td>
<td>App</td>
<td>1.0666</td>
<td>1.0</td>
<td>2024-02-28 07:01:56.004</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>HDHRoger'sMarket</td>
<td>2024-02-28 07:09:00</td>
<td>Pepperoni Protein Pack</td>
<td>9.999910e+10</td>
<td>3.0</td>
<td>order</td>
<td>01a6c049-a7f4-45ee-84fc-3fb8c9d7fc7a</td>
<td>51be7741-b716-4478-be50-ef2b5f52d69d</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>NTPM-JWO-Market Kitchen Active</td>
<td>App</td>
<td>0.9500</td>
<td>1.0</td>
<td>2024-02-28 07:08:03.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>HDHRoger'sMarket</td>
<td>2024-02-28 07:09:00</td>
<td>Dnkn Dnts Iced Coffee Vanilla</td>
<td>4.900007e+10</td>
<td>1.0</td>
<td>order</td>
<td>20bc02c6-bd1f-45c3-89c9-7dc1d9f6f259</td>
<td>e63a092b-2814-4358-a2f9-e9354c72d829</td>
<td>NTPM-JWO-BEVERAGES</td>
<td>NTPM-JWO-BEVERAGES</td>
<td>App</td>
<td>0.8500</td>
<td>1.0</td>
<td>2024-02-28 07:08:09.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>HDHRoger'sMarket</td>
<td>2024-02-28 07:17:00</td>
<td>Banana</td>
<td>9.999000e+10</td>
<td>1.0</td>
<td>order</td>
<td>fa0414df-e886-4a07-9410-ba87ecfda3a5</td>
<td>92e469b4-d9e7-4028-bb22-c7fb6fde6b8c</td>
<td>NTPM-JWO-RE-Produce</td>
<td>NTPM-JWO-RE-Produce</td>
<td>App</td>
<td>0.7666</td>
<td>1.0</td>
<td>2024-02-28 07:16:14.004</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>HDHRoger'sMarket</td>
<td>2024-02-28 07:26:00</td>
<td>Alta Dena Milk Whole 64oz</td>
<td>7.039910e+10</td>
<td>1.0</td>
<td>order</td>
<td>4bf7b510-5141-4597-b71f-06d2389c5b70</td>
<td>edeec561-2161-417a-8099-fd16999a961d</td>
<td>NTPM-JWO-BEV SOY MILK ALTERNATIVES</td>
<td>NTPM-JWO-BEV SOY MILK ALTERNATIVES</td>
<td>App</td>
<td>2.7666</td>
<td>1.0</td>
<td>2024-02-28 07:23:14.004</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="calculating-inventory-and-creating-inventory-build-up-diagram" class="level2">
<h2 class="anchored" data-anchor-id="calculating-inventory-and-creating-inventory-build-up-diagram">Calculating Inventory and creating Inventory Build-Up Diagram</h2>
<p>Now to create an inventory build-up diagram of the amount of customers in the store by minute, we’ll need to create a dataframe which lists every single possible minute in our time range from our data.</p>
<p>For our largest valued time, we’ll want to find the maximum in the purchase_datetime column, since that time will always come after the largest entry time.</p>
<p>For our smallest valued time, we’ll want to look at entry time, since that will always be smaller than the smallest purchase time.</p>
<div id="b2b934b0" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rogers[<span class="st">'purchase_datetime'</span>].<span class="bu">max</span>(), rogers[<span class="st">'entry_datetime'</span>].<span class="bu">min</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>(Timestamp('2024-02-28 23:01:00'), Timestamp('2024-02-28 07:01:56.004000'))</code></pre>
</div>
</div>
<p>The time range of the data is 07:01 to 23:01. We’ll do a minute before and after for our range to ensure we don’t miss anything that may be rounding up or down due to the number of seconds.</p>
<div id="c502cb9f" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>time_seq <span class="op">=</span> pd.date_range(start<span class="op">=</span><span class="st">"2024-02-28 07:00:00"</span>, end<span class="op">=</span><span class="st">"2024-02-28 23:05:00"</span>, freq<span class="op">=</span><span class="st">"T"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dt_customer_count <span class="op">=</span> pd.DataFrame({<span class="st">'time'</span>: time_seq, <span class="st">'customer_count'</span>: <span class="dv">0</span>})</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>dt_customer_count.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">time</th>
<th data-quarto-table-cell-role="th">customer_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-02-28 07:00:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-02-28 07:01:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-02-28 07:02:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-02-28 07:03:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-02-28 07:04:00</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The “freq = ‘T’” indicates we want the date_range by minute. Don’t ask me why it’s T for minute. “M” must be on a break…</p>
<p>Now, we must count each customer which is in the store at each minute listed in our dataframe. This gets slightly complicated for our code.</p>
<p>Below is just one way to go about it.</p>
<div id="86e3d57a" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> rogers.iterrows():</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    entry_time_rounded <span class="op">=</span> row[<span class="st">'entry_datetime'</span>].floor(<span class="st">'min'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> (dt_customer_count[<span class="st">'time'</span>] <span class="op">&gt;=</span> entry_time_rounded) <span class="op">&amp;</span> (dt_customer_count[<span class="st">'time'</span>] <span class="op">&lt;</span> row[<span class="st">'purchase_datetime'</span>])</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    dt_customer_count.loc[mask, <span class="st">'customer_count'</span>] <span class="op">+=</span> row[<span class="st">'group_size'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the above code, first we are iterrating over all the rows in the rogers dataframe, meaning we are getting the index for the row, and all the data in the row itself. We want to do this in order to go row by row, seeing if that person is either in the store, or not in the store based on their entry and purchase time.</p>
<p>We then round down the entry time to the nearest minute using the floor function.</p>
<p>This is where it can get tricky. The mask variable will return a boolean value (True or False) for every row in dt_customer_count dataframe where the time in the dt_customer_count dataframe is equal to or greater than the entry time of the customer, and where the the dt_customer_count time is less than the purchase time for that customer. Overall, this is returning a True or False for if the customer is in the store at that time.</p>
<p>Finally, we use the .loc function to locate rows where this is True, and add the group size to the customer count, since some customers come in groups.</p>
<p>Below is what the dataframe looks like:</p>
<div id="b4443a1d" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dt_customer_count.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">time</th>
<th data-quarto-table-cell-role="th">customer_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-02-28 07:00:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-02-28 07:01:00</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-02-28 07:02:00</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-02-28 07:03:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-02-28 07:04:00</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>What is the average number of customers in the app every minute?</p>
<div id="e37a5fbf" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>avg_inventory <span class="op">=</span> dt_customer_count[<span class="st">'customer_count'</span>].mean()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>avg_inventory</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>6.3395445134575565</code></pre>
</div>
</div>
<p>Now, let’s plot the inventory build-up diagram.</p>
<div id="e35ea19d" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>plt.plot(dt_customer_count[<span class="st">'time'</span>], dt_customer_count[<span class="st">'customer_count'</span>])</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Inventory Build-up Diagram"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Customers in the Store"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="throughput_files/figure-html/cell-17-output-1.png" width="808" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Going from 7:00 AM to 10:00 PM, it looks like there is slowly more and more people entering the store. There was also a large influx of people just around 4:00 PM (maybe that’s when people are out of work?).</p>
</section>
</section>
<section id="customers-entering-every-15-min" class="level1">
<h1>Customers entering every 15 Min</h1>
<p>Now, let’s look at how many customers are entering the app every 15 minutes to show different ways to look at the data.</p>
<p>We’ll use the same exact method as we did before to get the original customer count for every minute, but instead of comparing the “mask” variable to a time sequence that’s every minute, the distance or time between each interval will be 15 minutes.</p>
<p>This is shown below by the column “end_time”, which shows the original time sequence variable and then pd.Timedelta(minutes=15) added to it.</p>
<p>We then create a similar table as we did before to count our customers.</p>
<div id="c3840e03" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining 15-minute intervals and initializing counts</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dt_times_15min <span class="op">=</span> pd.DataFrame({<span class="st">'start_time'</span>: time_seq, <span class="st">'end_time'</span>: time_seq <span class="op">+</span> pd.Timedelta(minutes<span class="op">=</span><span class="dv">15</span>)})</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>dt_customer_count_15min <span class="op">=</span> pd.DataFrame({<span class="st">'start_time'</span>: time_seq, <span class="st">'customer_count'</span>: <span class="dv">0</span>})</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>dt_customer_count_15min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">start_time</th>
<th data-quarto-table-cell-role="th">customer_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-02-28 07:00:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-02-28 07:01:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-02-28 07:02:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-02-28 07:03:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-02-28 07:04:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">961</td>
<td>2024-02-28 23:01:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">962</td>
<td>2024-02-28 23:02:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">963</td>
<td>2024-02-28 23:03:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">964</td>
<td>2024-02-28 23:04:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">965</td>
<td>2024-02-28 23:05:00</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>966 rows × 2 columns</p>
</div>
</div>
</div>
<p>Now we’ll the count the number of customers entering the store in 15 minute intervals.</p>
<p>This does not mean from 7:00 AM to 7:15 AM, then 7:15 AM to 7:30 AM. It’s actually 7:00 AM to 7:15 AM, then 7:01 AM to 7:16 AM and so on.</p>
<p>We’ll do this using the same method as done previously when counting every minute.</p>
<div id="a2eb353c" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> rogers.iterrows():</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    entry_time_rounded <span class="op">=</span> row[<span class="st">'entry_datetime'</span>].floor(<span class="st">'min'</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> (dt_times_15min[<span class="st">'start_time'</span>] <span class="op">&lt;=</span> entry_time_rounded) <span class="op">&amp;</span> (dt_times_15min[<span class="st">'end_time'</span>] <span class="op">&gt;</span> row[<span class="st">'entry_datetime'</span>])</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    dt_customer_count_15min.loc[mask, <span class="st">'customer_count'</span>] <span class="op">+=</span> row[<span class="st">'group_size'</span>]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>dt_customer_count_15min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">start_time</th>
<th data-quarto-table-cell-role="th">customer_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-02-28 07:00:00</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-02-28 07:01:00</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-02-28 07:02:00</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-02-28 07:03:00</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-02-28 07:04:00</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">961</td>
<td>2024-02-28 23:01:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">962</td>
<td>2024-02-28 23:02:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">963</td>
<td>2024-02-28 23:03:00</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">964</td>
<td>2024-02-28 23:04:00</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">965</td>
<td>2024-02-28 23:05:00</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>966 rows × 2 columns</p>
</div>
</div>
</div>
<p>Notice this time, we put a start and end time in our time sequence (dt_times_15min) rather than just “time” which was every minute in the dt_customer_count. This changes our approach.</p>
<p>We want to know how many enter in the 15 minute time frame. The entry time will need to be greater than or equal to the start time and less than the end time for them to have entered the store in that interval.</p>
<p>For example, if a customer enters the app at 7:05 AM, they will add to the customer count for start times between 7:00 and 7:04.</p>
<p>Now lets plot the inventory diagram again.</p>
<div id="f079ccc0" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>plt.plot(dt_customer_count_15min[<span class="st">'start_time'</span>], dt_customer_count_15min[<span class="st">'customer_count'</span>])</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Inventory Build-up Diagram"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Customers entering the Store every 15 Minutes"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="throughput_files/figure-html/cell-20-output-1.png" width="808" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can see the number of customers entering the store initially is slowly rising, then it looks like a fairly steady average between Noon and 6 PM, then it take a spike at 6 PM and lowers back down with a sharp turn down at 11 PM.</p>
<p>We’ll calculate the average amount of customers entering the store every 15 minutes.</p>
<div id="a489d0ae" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dt_customer_count_15min[<span class="st">'customer_count'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>36.821946169772254</code></pre>
</div>
</div>
</section>
<section id="comparing-littles-law-calculations-to-data" class="level1">
<h1>Comparing Little’s Law Calculations to Data</h1>
<p>Now let’s get back to Little’s Law. We want to see if we can get the same results through Little’s Law as we do through directly calculating the parameter from the data set. Remember, Little’s law has 3 main parameters: Arrival rate, inventory or average number of customers in the process, and time spent in the process.</p>
<p>We’ll be comparing our time spent in process or duration from our data to the result from Little’s Law. Theoretically, we should get the same answers. However, errors can always occur in the process.</p>
<p>We already have average inventory, or customers in the process, so now we need arrival rate to calculate time in process.</p>
<p>There are multiple ways to go about this, but we’ll use the groupby method.</p>
<div id="a2665a9e" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># converting entry time to only list the hour they entered (hourly arrival rate)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>rogers[<span class="st">'entry_hour'</span>] <span class="op">=</span> rogers[<span class="st">'entry_datetime'</span>].dt.hour</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Grouping customers by entry hour summing the group size.</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>hourly_customer_count <span class="op">=</span> rogers.groupby(<span class="st">'entry_hour'</span>)[<span class="st">'group_size'</span>].<span class="bu">sum</span>().reset_index(name<span class="op">=</span><span class="st">'total_customers'</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing customers arriving after 11 PM (CLOSING TIME)</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>hourly_customer_count <span class="op">=</span> hourly_customer_count[hourly_customer_count[<span class="st">'entry_hour'</span>] <span class="op">!=</span> <span class="dv">23</span>]</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>hourly_customer_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">entry_hour</th>
<th data-quarto-table-cell-role="th">total_customers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>7</td>
<td>31.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>8</td>
<td>79.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>9</td>
<td>91.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10</td>
<td>132.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>11</td>
<td>140.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>12</td>
<td>189.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>13</td>
<td>163.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>14</td>
<td>161.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>15</td>
<td>154.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>16</td>
<td>149.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>17</td>
<td>143.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>18</td>
<td>195.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>19</td>
<td>184.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>20</td>
<td>205.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>21</td>
<td>183.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>22</td>
<td>173.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We need to calculate the average customers entering the app, so we’ll find the mean of the total_customers column</p>
<div id="cc796591" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>avg_customers_per_hour <span class="op">=</span> hourly_customer_count[<span class="st">'total_customers'</span>].mean()</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>avg_customers_per_hour</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>148.25</code></pre>
</div>
</div>
<p>Our average customer arrival rate per hour is 148.25.</p>
<p>Now we can use Little’s Law to calculate average trip duration.</p>
<p>To repeat, Little’s Law is <span class="math display">\[ L = \lambda * W \]</span>, but we’re solving for W. Tranforming the formula, we get <span class="math display">\[ W = L / \lambda  \]</span>, or average inventory divided by arrival rate.</p>
<div id="6fc1c148" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating average trip duration. Converting customers per hour to minutes.</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>trip_duration <span class="op">=</span> avg_inventory<span class="op">/</span>(avg_customers_per_hour<span class="op">/</span><span class="dv">60</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>trip_duration_min <span class="op">=</span> pd.to_timedelta(trip_duration, unit<span class="op">=</span><span class="st">'m'</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>trip_duration, trip_duration_min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>(2.565751573743362, Timedelta('0 days 00:02:33.945094421'))</code></pre>
</div>
</div>
<p>From Little’s Law, we calculated that the average trip duration was 2.566 minutes, or 2 minutes and 34 seconds.</p>
<p>Lets see how that compares to the trip duration average from the data.</p>
<div id="1bc8c35c" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating separate dataframe without any rows which have the customer arriving after 11 PM</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>rogers_before_11 <span class="op">=</span> rogers[rogers[<span class="st">'entry_hour'</span>] <span class="op">!=</span> <span class="dv">23</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating average </span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>duration_min <span class="op">=</span> np.average(rogers_before_11[<span class="st">'trip_duration_mins'</span>], weights<span class="op">=</span>rogers_before_11[<span class="st">'group_size'</span>])</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>duration_min_converted <span class="op">=</span> pd.to_timedelta(duration_min, unit<span class="op">=</span><span class="st">'m'</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>duration_min, duration_min_converted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>(2.1050608347386173, Timedelta('0 days 00:02:06.303650082'))</code></pre>
</div>
</div>
<p>Our calculated duration within the app was 2.1 minutes, 0.4 minutes or 27 seconds off from our duration calculated from Little’s Law.</p>
<p>This is likely due to our rounding down to the nearest minute minute for entry time using the floor function.</p>
<p>Overall, the results we calculated here could be used by the store to gauge effectiveness of site navigation improvements, targeting algorithms, payment process, and many other parts of the process when someone comes into the store. Little’s Law and it’s parameters are key metrics within the supply chain analytical field, helping stores and customers reach their optimal process flow.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>